Updated start scripts

diff --git a/distribution/ddf-common/src/main/resources/bin/ddf b/distribution/ddf-common/src/main/resources/bin/ddf
--- a/distribution/ddf-common/src/main/resources/bin/ddf
+++ b/distribution/ddf-common/src/main/resources/bin/ddf
@@ -33,13 +33,15 @@ get_property() {
     grep ^$1= "$PROPERTIES_FILE" | cut -d '=' -f2
 }
 
-
-# Extract values from Java properties file and construct Solr URL
-MANAGE_SOLR=$(get_property solr.managed)
-SOLR_PORT=$(get_property solr.http.port)
-TEMPLATE=$(get_property solr.http.url)
-PARTIAL_URL="$(echo $TEMPLATE | sed -e 's/\${solr.http.port}/PORT_PLACEHOLDER/')"
-SOLR_URL=${PARTIAL_URL/"PORT_PLACEHOLDER"/$SOLR_PORT}
+refresh_properties() {
+    # Extract values from Java properties file and construct Solr URL
+    MANAGE_SOLR=$(get_property solr.managed.internally)
+    SOLR_PORT=$(get_property solr.http.port)
+    SOLR_CLIENT=$(get_property solr.client)
+    TEMPLATE=$(get_property solr.http.url)
+    PARTIAL_URL="$(echo $TEMPLATE | sed -e 's/\${solr.http.port}/PORT_PLACEHOLDER/')"
+    SOLR_URL=${PARTIAL_URL/"PORT_PLACEHOLDER"/$SOLR_PORT}
+}
 
 # Return 0 (success/true) if the Solr lifecycle should be managed by this script
 is_managing_solr() {
@@ -100,7 +102,7 @@ start_solr() {
 
     # Does not check to see if Solr is running the Solr port; there is no guarantee
     # the Solr server is for this instance of DDF. It could have been started elsewhere.
-    $SOLR_EXEC restart -p $SOLR_PORT $(deny_remote_connection_option)
+    $SOLR_EXEC start -p $SOLR_PORT $(deny_remote_connection_option)
     local SOLR_START_RC=$?
         if [ "$SOLR_START_RC" -ne 0 ]; then
             echo "WARNING! Solr start returned error code, please check Solr logs"
@@ -128,7 +130,6 @@ set_solr_memory() {
 }
 
 stop_solr() {
-
     $SOLR_EXEC stop -p $SOLR_PORT
 }
 
@@ -157,11 +158,18 @@ start_karaf() {
 
 attempt_startup() {
     if is_managing_solr; then
+        if [ "$SOLR_CLIENT" != "HttpSolrClient" ]; then
+            echo "ERROR! solr.managed.internally is set to true but the solr.client is not HttpSolrClient"
+            echo "Please set solr.managed.internally to false if you are not using the HttpSolrClient and"
+            echo "do not want DDF to be managing the solr instance."
+            # Exit code 83, for ascii code S, for Solr!
+            exit 83
+        fi
         if is_protocol_https $SOLR_URL; then
             set_solr_https_properties
         fi
-            set_solr_memory
-            start_solr;
+        set_solr_memory
+        start_solr;
     else
         echo "Solr is not managed"
     fi
@@ -174,15 +182,16 @@ attempt_startup() {
 attempt_shutdown() {
     if is_restarting; then
         echo "Restarting JVM..."
-    else
         if is_managing_solr; then
             stop_solr
         fi
+    else
         exit $KARAF_EXEC_RC
     fi
 }
 
 while true; do
+    refresh_properties
     clear_restart_flag
     print_messages
     attempt_startup
